# Generated by Django 3.0.8 on 2020-07-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='defination',
            new_name='definition',
        ),
    ]
